name: EvenMoreFish
author: Oheers
version: ${project.version}
main: com.oheers.fish.EvenMoreFish
api-version: '1.20'
depend: [ Vault ]
softdepend: [ WorldGuard, PlaceholderAPI, RedProtect, mcMMO, AureliumSkills, ItemsAdder, HeadDatabase ]
loadbefore: [ AntiAC ]

commands:
  evenmorefish:
    usage: /<command> [name]
    aliases: [ emf ]
libraries:
  - com.zaxxer:HikariCP:5.0.1
  - org.flywaydb:flyway-core:9.22.3
  - com.github.ben-manes.caffeine:caffeine:3.1.8





#  There are roughly 300-400 moose roaming freely in the woods of Sweden